---
- hosts: all
  become: true
  tasks:
  - name: stop if we have old docker container
    command: docker-compose stop
    ignore_errors: yes

  - name: remove stopped docker container
    command: docker-compose rm -f
    ignore_errors: yes

  - name: remove current docker image
    command: docker-compose rm -v
    ignore_errors: yes

  - name: building docker image
    command: docker-compose up 
    args:
      chdir: /opt/docker
